openapi: 3.0.0
info:
  title: Gather API
  description: API for managing gathers
  version: 1.0.0
servers:
- url: /
paths:
  /api/gathers:
    get:
      summary: Get Gather by Google Place
      operationId: getGatherByGooglePlace
      parameters:
      - name: googleId
        in: query
        description: Google place ID
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: lat
        in: query
        description: Latitude of the location
        required: false
        style: form
        explode: true
        schema:
          type: number
          format: float
      - name: lng
        in: query
        description: Longitude of the location
        required: false
        style: form
        explode: true
        schema:
          type: number
          format: float
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gather'
      x-swagger-router-controller: Default
    post:
      summary: Create a new Gather
      operationId: createGather
      parameters:
      - name: googleId
        in: query
        description: Google place ID
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: lat
        in: query
        description: Latitude of the location
        required: true
        style: form
        explode: true
        schema:
          type: number
          format: float
      - name: lng
        in: query
        description: Longitude of the location
        required: true
        style: form
        explode: true
        schema:
          type: number
          format: float
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Gather'
        required: true
      responses:
        "201":
          description: Gather created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gather'
      x-swagger-router-controller: Default
  /api/gathers/{gatherId}/participants:
    post:
      summary: Add a new participant to the Gather
      operationId: addParticipantToGather
      parameters:
      - name: gatherId
        in: path
        description: ID of the Gather to which the participant will be added
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Participant'
        required: true
      responses:
        "201":
          description: Participant added to the gather
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Participant'
      x-swagger-router-controller: Default
components:
  schemas:
    PlaceFinderSuggestion:
      required:
      - label
      type: object
      properties:
        id:
          type: string
          format: uuid
        label:
          type: string
          maxLength: 20
    Participant:
      required:
      - name
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 20
      example:
        name: name
        id: id
    GatherLocation:
      required:
      - lat
      - lng
      type: object
      properties:
        name: 
          type: string
          maxLength: 20
        formattedAddress:
          type: string
          maxLength: 100
        googleId:
          type: string
          format: uuid
        lat:
          type: number
          format: float
        lng:
          type: number
          format: float
      example:
        name: Heidelberg
        formattedAddress: Heidelberg, Germany
        googleId: googleId
        lng: 6.0274563
        lat: 0.8008282
    Gather:
      required:
      - location
      - name
      - participants
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 20
        location:
          $ref: '#/components/schemas/GatherLocation'
        participants:
          type: array
          items:
            $ref: '#/components/schemas/Participant'
      example:
        name: Meeting in Heidelberg
        location:
          googleId: googleId
          name: Heidelberg
          formattedAddress: Heidelberg, Germany
          lng: 6.0274563
          lat: 0.8008282
        id: id
        participants:
        - name: Jan Böhmermann
          id: id
        - name: Bully Herbig
          id: id
